### ISSUE TITLE
Need to check parcel length on the server (Client hangs when parcel size is wrong)

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#148]
I recently created a parcel like this:

```toml
[[parcel]]
[parcel.label]
name = "examples/mkbindle.rs"
mediaType = "text/plain"
size = 1483
sha256 = "9f12ae3891d31fa9ec13089d6c9b8f46d1900c88a51a64f582f669fd4ec8a5ff"
[parcel.label.feature.wagi]
file = "true"
[parcel.conditions]
memberOf = ["files"]
```

But I had transposed the last two digits of `size`. It should have been `1438`.

When the Bindle server constructed the HTTP response, it set `Content-Length: 1483`, and then sent `1438` bytes.

That little typo broke the Bindle client, which listens until it has reached exactly the byte count from `Content-Length`. So the client will just hang with no error.

So probably we should at least fix this in the Bindle client. On the server, we should (a) check the content length of the parcel before sending or (b) verify the content length of the parcel on reception. These are not mutually exclusive; we could do both.
